FI.WebAtividadeEntrevista/Controllers/ClienteController.cs
using FI.AtividadeEntrevista.BLL;
using FI.AtividadeEntrevista.DML;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using WebAtividadeEntrevista.Models;

namespace WebAtividadeEntrevista.Controllers
{
    public class ClienteController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Incluir()
        {
            return View();
        }

        [HttpPost]
        public JsonResult Incluir(ClienteModel model)
        {
            BoCliente boCliente = new BoCliente();
            BoBeneficiario boBeneficiario = new BoBeneficiario();

            if (boCliente.VerificarExistencia(model.CPF, model.Email))
            {
                Response.StatusCode = 400;
                return Json("Já existe um cliente cadastrado com este CPF e/ou E-mail.");
            }

            if (!this.ModelState.IsValid)
            {
                List<string> erros = (from item in ModelState.Values
                                      from error in item.Errors
                                      select error.ErrorMessage).ToList();

                Response.StatusCode = 400;

                return Json(string.Join(Environment.NewLine, erros));
            }
            else
            {
                model.Id = boCliente.Incluir(new Cliente()
                {
                    CEP = model.CEP.ToUpper(),
                    CPF = model.CPF.ToUpper(),
                    Cidade = model.Cidade.ToUpper(),
                    Email = model.Email.ToUpper(),
                    Estado = model.Estado.ToUpper(),
                    Logradouro = model.Logradouro.ToUpper(),
                    Nacionalidade = model.Nacionalidade.ToUpper(),
                    Nome = model.Nome.ToUpper(),
                    Sobrenome = model.Sobrenome.ToUpper(),
                    Telefone = model.Telefone.ToUpper()
                });

                if (model.Beneficiarios != null && model.Beneficiarios.Any())
                {
                    var beneficiarios = model.Beneficiarios.Select(b => new Beneficiario
                    {
                        Nome = b.Nome.ToUpper(),
                        CPF = b.CPF.ToUpper(),
                        IdCliente = model.Id
                    }).ToList();

                    boBeneficiario.Incluir(beneficiarios);
                }

                return Json("Cadastro efetuado com sucesso!");
            }
        }

        [HttpPost]
        public JsonResult Alterar(ClienteModel model)
        {
            BoCliente boCliente = new BoCliente();
            BoBeneficiario boBeneficiario = new BoBeneficiario();

            bool clienteExistente = boCliente.VerificarExistenciaAlterar(model.CPF, model.Email, model.Id);

            if (clienteExistente )
            {
                Response.StatusCode = 400;
                return Json("Já existe um cliente cadastrado com este CPF e/ou E-mail.");
            }

            if (!this.ModelState.IsValid)
            {
                List<string> erros = (from item in ModelState.Values
                                      from error in item.Errors
                                      select error.ErrorMessage).ToList();

                Response.StatusCode = 400;

                return Json(string.Join(Environment.NewLine, erros));
            }
            else
            {
                boCliente.Alterar(new Cliente()
                {
                    Id = model.Id,
                    CEP = model.CEP.ToUpper(),
                    CPF = model.CPF.ToUpper(),
                    Cidade = model.Cidade.ToUpper(),
                    Email = model.Email.ToUpper(),
                    Estado = model.Estado.ToUpper(),
                    Logradouro = model.Logradouro.ToUpper(),
                    Nacionalidade = model.Nacionalidade.ToUpper(),
                    Nome = model.Nome.ToUpper(),
                    Sobrenome = model.Sobrenome.ToUpper(),
                    Telefone = model.Telefone.ToUpper()
                });

                boBeneficiario.Excluir(model.Id);

                if (model.Beneficiarios != null && model.Beneficiarios.Any())
                {
                    var beneficiarios = model.Beneficiarios.Select(b => new Beneficiario
                    {
                        Nome = b.Nome.ToUpper(),
                        CPF = b.CPF.ToUpper(),
                        IdCliente = model.Id
                    }).ToList();

                    boBeneficiario.Incluir(beneficiarios);
                }

                return Json("Cliente alterado com sucesso!");
            }
        }


        [HttpGet]
        public ActionResult Alterar(long id)
        {
            BoCliente boCliente = new BoCliente();
            BoBeneficiario boBeneficiario = new BoBeneficiario();
            Cliente cliente = boCliente.Consultar(id);
            ClienteModel model = null;

            if (cliente != null)
            {
                model = new ClienteModel()
                {
                    Id = cliente.Id,
                    CEP = cliente.CEP,
                    CPF = cliente.CPF,
                    Cidade = cliente.Cidade,
                    Email = cliente.Email,
                    Estado = cliente.Estado,
                    Logradouro = cliente.Logradouro,
                    Nacionalidade = cliente.Nacionalidade,
                    Nome = cliente.Nome,
                    Sobrenome = cliente.Sobrenome,
                    Telefone = cliente.Telefone,
                    Beneficiarios = boBeneficiario.Consultar(cliente.Id).Select(b => new BeneficiarioModel
                    {
                        Nome = b.Nome,
                        CPF = b.CPF
                    }).ToList()
                };
            }

            return View(model);
        }

        [HttpPost]
        public JsonResult Excluir(long id)
        {
            try
            {
                BoCliente boCliente = new BoCliente();
                BoBeneficiario boBeneficiario = new BoBeneficiario();

                boBeneficiario.Excluir(id);
                boCliente.Excluir(id);

                return Json(new { Result = "OK", Message = "Cliente excluído com sucesso!" });
            }
            catch (Exception ex)
            {
                Response.StatusCode = 500;

                return Json(new { Result = "ERROR", Message = ex.Message });
            }
        }

        [HttpPost]
        public JsonResult ClienteList(int jtStartIndex = 0, int jtPageSize = 0, string jtSorting = null)
        {
            try
            {
                int qtd = 0;
                string campo = string.Empty;
                string crescente = string.Empty;
                string[] array = jtSorting.Split(' ');

                if (array.Length > 0)
                    campo = array[0];

                if (array.Length > 1)
                    crescente = array[1];

                List<Cliente> clientes = new BoCliente().Pesquisa(jtStartIndex, jtPageSize, campo, crescente.Equals("ASC", StringComparison.InvariantCultureIgnoreCase), out qtd);

                return Json(new { Result = "OK", Records = clientes, TotalRecordCount = qtd });
            }
            catch (Exception ex)
            {
                return Json(new { Result = "ERROR", Message = ex.Message });
            }
        }
    }
}

FI.WebAtividadeEntrevista/Views/Cliente/Alterar.cshtml
@model WebAtividadeEntrevista.Models.ClienteModel

@{
    ViewBag.Title = "Alterar Cliente";
}

@section scripts{
    <script>
        var urlPost = '@Url.Action("Alterar", "Cliente", new { area = "" })';
        var obj = @Html.Raw(Json.Encode(Model));
        var urlRetorno = '@Url.Action("Index", "Cliente", new { area = "" })';
    </script>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryui")
    @Scripts.Render("~/bundles/jquerymask")
    @Scripts.Render("~/bundles/validaCPF")
    @Scripts.Render("~/bundles/altClientes")
    @Scripts.Render("~/bundles/Beneficiarios")
}

<h1 class="display-5">@Html.Raw(ViewBag.Title)</h1>

@Html.Partial("Forms")

@Html.Partial("_ModalBeneficiarios")

FI.WebAtividadeEntrevista/Views/Cliente/Forms.cshtml
<form id="formCadastro" method="post" class="mt-4">
    <div class="row">
        <div class="col-md-6">
            <div class="mb-3">
                <label for="Nome" class="form-label">Nome:</label>
                <input required="required" type="text" class="form-control" id="Nome" name="Nome" placeholder="Ex.: Nathan" maxlength="50">
            </div>
        </div>
        <div class="col-md-6">
            <div class="mb-3">
                <label for="Sobrenome" class="form-label">Sobrenome:</label>
                <input required="required" type="text" class="form-control" id="Sobrenome" name="Sobrenome" placeholder="Ex.: da Silva" maxlength="255">
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-6">
            <div class="mb-3">
                <label for="CPF" class="form-label">CPF:</label>
                <input required="required" type="text" class="form-control cpf" id="CPF" name="CPF" placeholder="Ex.: 123.456.789-00" maxlength="14">
            </div>
        </div>
        <div class="col-md-6">
            <div class="mb-3">
                <label for="Nacionalidade" class="form-label">Nacionalidade:</label>
                <input required="required" type="text" class="form-control" id="Nacionalidade" name="Nacionalidade" placeholder="Ex.: brasileira" maxlength="50">
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-4">
            <div class="mb-3">
                <label for="CEP" class="form-label">CEP:</label>
                <input required="required" type="text" class="form-control" id="CEP" name="CEP" placeholder="Ex.: 01011-100" maxlength="9">
            </div>
        </div>
        <div class="col-md-4">
            <div class="mb-3">
                <label for="Estado" class="form-label">Estado:</label>
                <select required="required" id="Estado" class="form-select" name="Estado">
                    <option value="">Selecione</option>
                    <option value="MG">Minas Gerais</option>
                    <option value="PE">Pernambuco</option>
                    <option value="SP">São Paulo</option>
                </select>
            </div>
        </div>
        <div class="col-md-4">
            <div class="mb-3">
                <label for="Cidade" class="form-label">Cidade:</label>
                <input required="required" type="text" class="form-control" id="Cidade" name="Cidade" maxlength="50" placeholder="Ex.: São Paulo">
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <div class="mb-3">
                <label for="Logradouro" class="form-label">Logradouro:</label>
                <input required="required" type="text" class="form-control" id="Logradouro" name="Logradouro" placeholder="Ex.: Rua Boa Vista 253" maxlength="500">
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-6">
            <div class="mb-3">
                <label for="Email" class="form-label">E-mail:</label>
                <input required="required" type="text" class="form-control" id="Email" name="Email" placeholder="Ex.: email@email.com" maxlength="2079">
            </div>
        </div>
        <div class="col-md-6">
            <div class="mb-3">
                <label for="Telefone" class="form-label">Telefone:</label>
                <input required="required" type="tel" class="form-control" id="Telefone" name="Telefone" placeholder="Ex.: (11) 2020-3030" maxlength="15">
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-12">
            <div class="row">
                <div class="col-md-6">
                    <button id="btnAbrirModalBeneficiarios" type="button" class="btn btn-sm btn-primary">Beneficiários</button>
                </div>
                <div class="col-md-6 text-end">
                    <button type="submit" class="btn btn-sm btn-success">Salvar</button>
                    @Html.ActionLink("Voltar", "Index", "Cliente", new { }, new { @class = "btn btn-sm btn-danger" })
                </div>
            </div>
        </div>
    </div>
</form>

FI.WebAtividadeEntrevista/Views/Cliente/Incluir.cshtml
@{
    ViewBag.Title = "Cadastrar Cliente";
}

@section scripts{
    <script>
        var urlPost = '@Url.Action("Incluir", "Cliente", new { area = "" })';
    </script>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryui")
    @Scripts.Render("~/bundles/jquerymask")
    @Scripts.Render("~/bundles/validaCPF")
    @Scripts.Render("~/bundles/clientes")
    @Scripts.Render("~/bundles/beneficiarios")
}

<h1 class="display-5">@Html.Raw(ViewBag.Title)</h1>

@Html.Partial("Forms")

@Html.Partial("_ModalBeneficiarios")

FI.WebAtividadeEntrevista/Views/Cliente/Index.cshtml
@{
    ViewBag.Title = "Clientes";
}

@section scripts{
    <script>
        var urlAlteracao = '@Url.Action("Alterar", "Cliente", new { area = "" })';
        var urlClienteList = '@Url.Action("ClienteList", "Cliente", new { area = "" })';
    </script>
    @Scripts.Render("~/bundles/listClientes")
}

<h1 class="display-5">@Html.Raw(ViewBag.Title)</h1>

<div class="row">
    <div class="col-lg-12 text-end mb-2">
        @Html.ActionLink("Novo Cliente", "Incluir", "Cliente", new { }, new { @class = "btn btn-sm btn-primary" })
    </div>
</div>

<table id="gridClientes" class="table"></table>

@Html.Partial("_ModalExcluirCliente")

FI.WebAtividadeEntrevista/Views/Cliente/_ModalBeneficiarios.cshtml
<div id="modalBeneficiarios" class="modal fade" tabindex="-1" aria-labelledby="modalBeneficiariosLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="modalBeneficiariosLabel">Beneficiários</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <form id="formBeneficiario">
                    <div class="row">
                        <div class="col-12 col-md-5 mb-3">
                            <div class="form-group">
                                <label for="cpf">CPF</label>
                                <input type="text" class="form-control cpf" id="cpf" placeholder="Ex.: 123.456.789-00" maxlength="14">
                            </div>
                        </div>
                        <div class="col-12 col-md-5 mb-3">
                            <div class="form-group">
                                <label for="nome">Nome</label>
                                <input type="text" class="form-control" id="nome" placeholder="Ex.: Nathan" maxlength="50">
                            </div>
                        </div>
                        <div class="col-12 col-md-2 d-flex align-items-end mb-3">
                            <div class="form-group w-100">
                                <button type="button" id="btnIncluir" class="btn btn-success w-100 d-flex justify-content-center">Incluir</button>
                            </div>
                        </div>
                    </div>
                </form>
                <table class="table table-striped mt-4" id="tabelaBeneficiarios">
                    <thead>
                        <tr>
                            <th>CPF</th>
                            <th>Nome</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody id="listaBeneficiarios">
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

FI.WebAtividadeEntrevista/Views/Cliente/_ModalExcluirCliente.cshtml
<div class="modal fade" id="modalConfirmacao" tabindex="-1" aria-labelledby="modalConfirmacaoLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="modalConfirmacaoLabel"></h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body text-center">
                <p>Tem certeza que deseja excluir este cliente?</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancelar</button>
                <button type="button" id="confirmarExclusao" class="btn btn-danger">Excluir</button>
            </div>
        </div>
    </div>
</div>